[project]
name = "integration-testing"
version = "1.0.6"
description = "Blackbox testing infrastructure to test and run marketplace integration scripts locally using mocks."
readme = "README.md"
authors = [
    { name = "talshapir", email = "talshapir@google.com" }
]
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.13",
    "environmentcommon",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "soar-sdk",
    "tipcommon",
    "yarl>=1.20.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.16.0",
    "pytest>=8.4.0",
    "pytest-xdist>=3.7.0",
    "ruff>=0.11.13",
    "types-pyyaml>=6.0.12.20250516",
    "types-requests>=2.32.0.20250611",
]

[tool.mypy]
exclude = [
    '\.?venv',
    'build',
    'dist',
]

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "--import-mode=importlib",
]
testpaths = [
    "tests/",
]

[tool.uv.sources]
tipcommon = { path = "../TIPCommon-2.0.6/TIPCommon-2.0.6-py2.py3-none-any.whl" }
environmentcommon = { path = "../EnvironmentCommon-1.0.2/EnvironmentCommon-1.0.2-py2.py3-none-any.whl" }
soar-sdk = { git = "https://github.com/chronicle/soar-sdk.git" }
